In [1]:
from autograder_term2week5 import *
_globals = globals()
import numpy as np
import numpy.testing as npt
import math
import matplotlib.pyplot as plt
from time import time
%matplotlib inline

Autograder loaded successfully!
Remember to always restart and run all from the Kernel menu before submitting!


# <center> Introduction to Mathematical Computing </center>
### <center>Phil Ramsden, Boumediene Hamzi, Sam Brzezicki, Matt Woolway</center>

# <center> Worksheet 9: Using numpy in Programming</center>

**NOTE:** When answering a question, remember to remove the `raise NotImplementedError()` line.

## Question 1 (i)

(a) Use the `range` function from "core Python" to create a `range` object called `myrange` containing the ints $97, 98, \dots, 102$. Then create a list called `mylist` containing the same ints. Finally, use NumPy's `arange` function to create a one-dimensional NumPy array called `myarray` containing the same ints.

In [2]:
myrange = range(97, 103)
mylist = [n for n in myrange]
myarray = np.arange(97,103)

print(myrange)
print(mylist)
print(myarray)

range(97, 103)
[97, 98, 99, 100, 101, 102]
[ 97  98  99 100 101 102]


In [3]:
# 3 Marks
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question1ia(_globals)

myrange contains the right numbers
myrange is a range
First test passed!

mylist contains the right numbers
mylist is a list
Second test passed!

myarray contains the right numbers
myarray is a numpy array
Final test passed!

3 out of 3


3

(b) Write a `for` loop that iterates through `myrange`, printing the squares. Do the same for `mylist`, and attempt the same for `myarray`. Then state which of the following is true.

<ol>
    <li>You can iterate across <code>range</code> objects, Python lists and 1D NumPy arrays using a <code>for</code> loop, and afterwards, all three are unchanged.</li>
    <li>You can iterate across <code>range</code> objects, Python lists and 1D NumPy arrays using a <code>for</code> loop, and afterwards, all three have become empty.</li>
    <li>You can iterate across <code>range</code> objects, Python lists and 1D NumPy arrays using a <code>for</code> loop, and afterwards, only the NumPy array has become empty.</li>
    <li>You can iterate across <code>range</code> objects and Python lists, but not 1D NumPy arrays, using a <code>for</code> loop.</li>
</ol>

In [4]:


question1ib_answer = 1

In [5]:
# 1 Mark
assert(question1ib_answer == question1ib())
print('test case passed!')

test case passed!


(c) Write a list comprehension that iterates across `myrange`, generating a list of all the squares; call it `range_squares`. Do the same for `mylist` (call it `list_squares`), and attempt the same for `my_array` (call it `array_squares` if it works).

In [6]:
range_squares = [n ** 2 for n in myrange]

list_squares = [n ** 2 for n in mylist]

array_squares = [n**2 for n in myarray]

print(range_squares)
print(list_squares)
print(array_squares)

[9409, 9604, 9801, 10000, 10201, 10404]
[9409, 9604, 9801, 10000, 10201, 10404]
[9409, 9604, 9801, 10000, 10201, 10404]


In [7]:
# 3 Marks
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question1ic(_globals)

range_squares contains the right numbers
range_squares is a list
First test passed!

list_squares contains the right numbers
list_squares is a list
Second test passed!

list_squares contains the right numbers
array_squares is a list
Final test passed!

3 out of 3


3

(d) State which of the following is true.

<ol>
    <li>You can iterate across <code>range</code> objects, Python lists and 1D NumPy arrays using a comprehension, and afterwards, all three are unchanged.</li>
    <li>You can iterate across <code>range</code> objects, Python lists and 1D NumPy arrays using a comprehension, and afterwards, all three have become empty.</li>
    <li>You can iterate across <code>range</code> objects, Python lists and 1D NumPy arrays using a comprehension, and afterwards, only the NumPy array has become empty.</li>
    <li>You can iterate across <code>range</code> objects and Python lists, but not 1D NumPy arrays, using a comprehension.</li>
</ol>

In [8]:
print(mylist, myrange, myarray)

question1id_answer = 1

[97, 98, 99, 100, 101, 102] range(97, 103) [ 97  98  99 100 101 102]


In [9]:
# 1 Mark
assert(question1id_answer == question1id())
print('test case passed!')

test case passed!


(e) From `myarray`, create a NumPy array consisting of all the squares; call it `square_array`. Do this in the simplest way possible, without using a loop or a comprehension. (Autograding won't be able to tell whether you've done that, though.)

In [10]:
square_array = myarray**2

print(square_array)

print(np.array([[0, 1, 2, 3], [0, 1, 2, 3] ,[0, 1, 2, 3]]))

[ 9409  9604  9801 10000 10201 10404]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


In [11]:
# 1 Mark
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question1ie(_globals)

square_array contains the right numbers
square_array is a numpy array

1 out of 1


1

(ii) Here's a simple lambda-expression:

In [12]:
add2 = lambda x, y : x + y

This should be read as "Let add2 be the function of $x$ and $y$ that adds $x$ to $y$." Then 

```python
add2(3, 4)
```

will return 7, and so on.

(a) Use NumPy's `fromfunction` function, and the lambda-expression `add2` defined above, to create the 2d array `mat1`, which is equal to
$$\left(
\begin{array}{rrrr}
0.0&1.0&2.0&3.0\\
1.0&2.0&3.0&4.0\\
2.0&3.0&4.0&5.0
\end{array}\right).$$

In [14]:
mat1 = np.fromfunction(add2, (3, 4))
print(mat1)

[[0. 1. 2. 3.]
 [1. 2. 3. 4.]
 [2. 3. 4. 5.]]


In [15]:
# 1 Mark
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question1iia(_globals)

Test passed!

1 out of 1


1

(b) Using NumPy's `nditer` function in a comprehension, create a list `squares1` of the squares of the entries of `mat1`, where the iteration is row-by-row; it should therefore begin

```python
[0.0, 1.0, 4.0, 9.0, 1.0, 4.0, ...
 ```

In [18]:
squares1 = [x**2 for x in np.nditer(mat1)]

print(squares1)

[0.0, 1.0, 4.0, 9.0, 1.0, 4.0, 9.0, 16.0, 4.0, 9.0, 16.0, 25.0]


In [19]:
# 1 Mark
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question1iib(_globals)

Test passed!

1 out of 1


1

(c) Using NumPy's `nditer` function in a comprehension, create a list `squares2` of the squares of the entries of `mat1`, where the iteration is column-by-colum; it should therefore begin

```python
[0.0, 1.0, 4.0, 1.0, 4.0, 9.0, ...
 ```

In [21]:
squares2 = [x**2 for x in np.nditer(mat1, order = 'F')]

print(squares2)

[0.0, 1.0, 4.0, 1.0, 4.0, 9.0, 4.0, 9.0, 16.0, 9.0, 16.0, 25.0]


In [22]:
# 1 Mark
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question1iic(_globals)

Test passed!

1 out of 1


1

(d) Using `fromfunction` with suitable lambda-expressions, create the 2d arrays `mat2`, `mat3` and `mat4`, respectively equal to

$$\left(
\begin{array}{rrrr}
0.0&1.0&2.0&3.0\\
1.0&0.0&1.0&2.0\\
2.0&1.0&0.0&1.0
\end{array}\right),\left(
\begin{array}{rrrr}
0.0&1.0&4.0&9.0
\end{array}\right)\mbox{ and }\left(
\begin{array}{rrrr}
0.0&1.0&4.0&9.0\\
-1.0&0.0&3.0&8.0\\
-4.0&-3.0&0.0&5.0\\
-9.0&-8.0&-5.0&0.0
\end{array}\right)$$

In [26]:
mat2 = np.fromfunction(lambda i,j: abs(i - j), (3,4))

mat3 = np.fromfunction(lambda i,j: (i + j) ** 2, (1,4))

mat4 = np.fromfunction(lambda i,j: j ** 2 - i ** 2, (4,4))

print(mat2)
print(mat3)
print(mat4)

[[0. 1. 2. 3.]
 [1. 0. 1. 2.]
 [2. 1. 0. 1.]]
[[0. 1. 4. 9.]]
[[ 0.  1.  4.  9.]
 [-1.  0.  3.  8.]
 [-4. -3.  0.  5.]
 [-9. -8. -5.  0.]]


In [27]:
# 3 Marks
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question1iid(_globals)

mat2 is correct

mat3 is correct

mat4 is correct

3 out of 3


3

(e) Run the following code:

In [28]:
for a, b in np.nditer((mat1, mat2)):
    print((float(a), float(b), a > b))

(0.0, 0.0, False)
(1.0, 1.0, False)
(2.0, 2.0, False)
(3.0, 3.0, False)
(1.0, 1.0, False)
(2.0, 0.0, True)
(3.0, 1.0, True)
(4.0, 2.0, True)
(2.0, 2.0, False)
(3.0, 1.0, True)
(4.0, 0.0, True)
(5.0, 1.0, True)


Then attempt it using `mat3` and `mat4` in place of `mat2`. Then choose which of the following statements is true:

<ol>
    <li>The <code>nditer</code> function allows you to iterate across two 2d arrays at the same time, but only if they're the same shape.</li>
    <li>The <code>nditer</code> function allows you to iterate across two 2d arrays at the same time, but only if their shapes are such that you could, for example, add them.</li>
    <li>The <code>nditer</code> function does not support iteration across two 2d arrays at the same time.</li>
</ol>

In [29]:


question1iie_answer = 2

In [30]:
# 1 Mark
assert(question1iie_answer == question1iie())
print('test case passed!')

test case passed!


## Question 2

(a) Write and test a function called `simpsons_rule1`. The function should take as its arguments:
<ul>
    <li>a function <code>func</code> from the reals to the reals;</li>
    <li>a float, or int, <code>xmin</code>;</li>
    <li>a float, or int, <code>xmax</code>;</li>
    <li>a positive even int <code>n</code>, with default value 10.</li>
</ul>

It should then return an approximate value for the integral of <code>func(x)</code> with respect to <code>x</code> between <code>xmin</code> and <code>xmax</code>, obtained by using the Simpson's rule formula

$$I \approx \frac{h}{3}\,\left(y_0 + 4\,y_1 + 2\,y_2 + \dots + 2\,y_{n-2}+4\,y_{n-1} + y_n\right),$$

where $h$, the step size, is obtained by dividing the interval width by <code>n</code>.

Your function should make no use of NumPy functionality, but should rely entirely either on loops, or on comprehensions, or both.

Test your function: for example

```python
import math
print(simpsons_rule1(math.sin, 0.0, math.pi/2))
```
should give something pretty close to 1.00000339.

In [2]:
def simpsons_rule1(func, xmin, xmax, n=10):
    import math
    #docstring
    h = (xmax - xmin) / n
    x = [(xmin + h * r) for r in range(0, n+1)]
    y = [func(r) for r in x]
    I = y[0]
    for r in range(1,n):
        if r % 2 == 0:
            I = I + 2 * y[r]
        if r % 2 == 1:
            I = I + 4 * y[r]
    I = I + y[n]
    return I * h /3
import math
print(simpsons_rule1(math.sin, 0, math.pi / 2))

1.0000033922209004


In [3]:
# No marks: function test

try:
    assert(np.isclose(simpsons_rule1(math.sin, 0, math.pi/2), 1.00000339))
except:
    print('Test failed!')
else:
    print('Test passed!')

Test passed!


In [4]:
# 4 Marks
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question2a(_globals)

Test with positional value of n passed!

Test with keyword value of n passed!

Test with default value of n passed!

This function does not seem to have a docstring

3 out of 4


3

(b) Write a function called <code>simpsons_rule2</code> that takes the same arguments and defaults as <code>simpsons_rule1</code>, and also returns the Simpson's rule approximation to the integral, but uses no loops or comprehensions. Instead, it should use NumPy arrays, vectorized operations and the `sum` function.

Test your function: for example

```python
import numpy as np
print(simpsons_rule2(np.sin, 0.0, np.pi/2))
```
should give something pretty close to 1.00000339.

In [9]:
def simpsons_rule2(func, xmin, xmax, n=10):
    import numpy as np
    h = (xmax - xmin) / n
    x = np.linspace(xmin, xmax, n+1)
    print(x)
    y = func(x)
    print(y)
    I = y[0]
    for r in range(1,n):
        if r % 2 == 0:
            I = I + 2 * y[r]
        if r % 2 == 1:
            I = I + 4 * y[r]
    I = I + y[n]
    return I * h /3
import numpy as np
print(simpsons_rule2(np.sin, 0.0, np.pi/2))

[0.         0.15707963 0.31415927 0.4712389  0.62831853 0.78539816
 0.9424778  1.09955743 1.25663706 1.41371669 1.57079633]
[0.         0.15643447 0.30901699 0.4539905  0.58778525 0.70710678
 0.80901699 0.89100652 0.95105652 0.98768834 1.        ]
1.0000033922209004


In [10]:
# No marks: function test

try:
    assert(np.isclose(simpsons_rule2(np.sin, 0, np.pi/2), 1.00000339))
except:
    print('Test failed!')
else:
    print('Test passed!')

[0.         0.15707963 0.31415927 0.4712389  0.62831853 0.78539816
 0.9424778  1.09955743 1.25663706 1.41371669 1.57079633]
[0.         0.15643447 0.30901699 0.4539905  0.58778525 0.70710678
 0.80901699 0.89100652 0.95105652 0.98768834 1.        ]
Test passed!


In [11]:
# 4 Marks
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question2b(_globals)

[0.         0.07853982 0.15707963 0.23561945 0.31415927 0.39269908
 0.4712389  0.54977871 0.62831853 0.70685835 0.78539816 0.86393798
 0.9424778  1.02101761 1.09955743 1.17809725 1.25663706 1.33517688
 1.41371669 1.49225651 1.57079633]
[0.         0.0784591  0.15643447 0.23344536 0.30901699 0.38268343
 0.4539905  0.52249856 0.58778525 0.64944805 0.70710678 0.76040597
 0.80901699 0.85264016 0.89100652 0.92387953 0.95105652 0.97236992
 0.98768834 0.99691733 1.        ]
Test with positional value of n passed!

[0.         0.09817477 0.19634954 0.29452431 0.39269908 0.49087385
 0.58904862 0.68722339 0.78539816 0.88357293 0.9817477  1.07992247
 1.17809725 1.27627202 1.37444679 1.47262156 1.57079633]
[0.         0.09801714 0.19509032 0.29028468 0.38268343 0.47139674
 0.55557023 0.63439328 0.70710678 0.77301045 0.83146961 0.88192126
 0.92387953 0.95694034 0.98078528 0.99518473 1.        ]
Test with keyword value of n passed!

[0.         0.15707963 0.31415927 0.4712389  0.62831853 0.78539816


3

(c) Suppose

```python
f = lambda x: x**5 - x**4
```

Which of the following statements is true?

<ol>
    <li>Both of my Simpson's Rule functions work if <code>f</code> is a lambda-expression like this.</li>
    <li>Only the first version, based on loops or comprehensions, works if <code>f</code> is a lambda-expression like this.</li>
    <li>Only the second version, based on vectorization, works if <code>f</code> is a lambda-expression like this.</li>    
    <li>Neither of my Simpson's Rule functions work if <code>f</code> is a lambda-expression like this.</li>
</ol>

In [73]:


question2c_answer = 1

In [74]:
# 1 Mark
assert(question2c_answer == question2c())
print('test case passed!')

test case passed!


(d) Suppose

```python
f = math.sin
```

Which of the following statements is true?

<ol>
    <li>Both of my Simpson's Rule functions work if <code>f</code> is a <code>math</code> function like this.</li>
    <li>Only the first version, based on loops or comprehensions, works if <code>f</code> is a <code>math</code> function like this.</li>
    <li>Only the second version, based on vectorization, works if <code>f</code> is a <code>math</code> function like this.</li>    
    <li>Neither of my Simpson's Rule functions work if <code>f</code> is a <code>math</code> function like this.</li>
</ol>

In [77]:


question2d_answer = 2

In [78]:
# 1 Mark
assert(question2d_answer == question2d())
print('test case passed!')

test case passed!


(e) Suppose

```python
f = np.sin
```

Which of the following statements is true?

<ol>
    <li>Both of my Simpson's Rule functions work if <code>f</code> is a NumPy function like this.</li>
    <li>Only the first version, based on loops or comprehensions, works if <code>f</code> is a NumPy function like this.</li>
    <li>Only the second version, based on vectorization, works if <code>f</code> is a NumPy function like this.</li>    
    <li>Neither of my Simpson's Rule functions work if <code>f</code> is a NumPy function like this.</li>
</ol>

In [81]:


question2e_answer = 1

In [82]:
# 1 Mark
assert(question2e_answer == question2e())
print('test case passed!')

test case passed!


(f) Use both your functions to calculate an estimate for
$$\int_0^{\pi/2}\sin x\,dx$$
using `n = 5000000` (this is actually a silly thing to do, since rounding error soon mounts up and overwhelms any gains from using more sub-intervals).

Use the `time` function from the `time` module to time both operations.

Which of the following statements is true?
<ol>
    <li>Each of my Simpson's Rule functions executes in a similar time for large <code>n</code>.</li>
    <li>The first version, based on loops or comprehensions, executes in a shorter time for large <code>n</code>.</li>
    <li>The second version, based on vectorization, executes in a shorter time for large <code>n</code>.</li>
</ol>

In [83]:


question2f_answer = 3

In [84]:
# 1 Mark
assert(question2f_answer == question2f())
print('test case passed!')

test case passed!


## Question 3

The <b>Arnol'd sine map</b> is a discrete-time dynamical model for the behaviour of certain types of nonlinear oscillator. It takes the form of a function of a variable $\theta$:

$$f_{\Omega, K}(\theta) = \theta + \Omega - \frac{K}{2\,\pi}\,\sin(2\,\pi\,\theta).$$

(a) Write and test two versions of an Arnol'd sine map function, called `sine_map1` and `sine_map2`. Each should take as its arguments three floats, standing for values of $\Omega$, $K$ and $\theta$, and return a single float equal to $f_{\Omega,K}(\theta).$ The first should use only functions and constants from the `math` module, and the second only functions and constants from NumPy. 

Good values for $\Omega$, $K$ and $\theta$ are $0.3$, $1.0$ and $0.3$ respectively.

In [12]:
def sine_map1(omega = 0.3, k = 1, theta = 0.3):
    import math
    f = theta + omega - (k / (2 * math.pi)) * math.sin(2 * math.pi * theta)
    return f

def sine_map2(omega = 0.3, k = 1, theta = 0.3):
    import numpy as np
    f = theta + omega - (k / (2 * np.pi)) * np.sin(2 * np.pi * theta)
    return f

In [13]:
# No marks: test cell

try:
    assert(np.isclose(sine_map1(0.3, 1.0, 0.3), 0.6 - 1.0/(2*np.pi) * np.sin(2*np.pi*0.3)))
    assert(np.isclose(sine_map2(0.3, 1.0, 0.3), 0.6 - 1.0/(2*np.pi) * np.sin(2*np.pi*0.3)))
except:
    print('Test failed!')
else:
    print('Test passed!')

Test passed!


In [14]:
# 2 Marks
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question3a(_globals)

Test of sine_map1 passed!

Test of sine_map2 passed!

2 out of 2


2

(b) Which of the following statements is true:

<ol>
    <li>If $K$ and $\theta$ are floats, and $\Omega$ is a one-dimensional NumPy array, both of my sine map functions work.</li>
    <li>If $K$ and $\theta$ are floats, and $\Omega$ is a one-dimensional NumPy array, only the first version, based on <code>math</code> functions, works.</li>
    <li>If $K$ and $\theta$ are floats, and $\Omega$ is a one-dimensional NumPy array, only the second version, based on NumPy functions, works.</li>
    <li>If $K$ and $\theta$ are floats, and $\Omega$ is a one-dimensional NumPy array, neither of my sine map functions works.</li>
</ol>

In [18]:


question3b_answer = 1

In [19]:
# 1 Mark
assert(question3b_answer == question3b())
print('test case passed!')

test case passed!


(c) Which of the following statements is true:

<ol>
    <li>If $\Omega$ and $K$ are floats, and $\theta$ is a one-dimensional NumPy array, both of my sine map functions work.</li>
    <li>If $\Omega$ and $K$ are floats, and $\theta$ is a one-dimensional NumPy array, only the first version, based on <code>math</code> functions, works.</li>
    <li>If $\Omega$ and $K$ are floats, and $\theta$ is a one-dimensional NumPy array, only the second version, based on NumPy functions, works.</li>
    <li>If $\Omega$ and $K$ are floats, and $\theta$ is a one-dimensional NumPy array, neither of my sine map functions works.</li>
</ol>

In [22]:


question3c_answer = 3

In [23]:
# 1 Mark
assert(question3c_answer == question3c())
print('test case passed!')

test case passed!


(d) The <b>rotation number</b> of the Arnol'd sine map, $\omega_{\Omega, K}(\theta_0)$, can be defined to be
$$\lim_{n\to\infty}\frac{\theta_n-\theta_0}{n},$$
where $\theta_0, \theta_1, \dots, \theta_n$ are successive iterates of the sine map. An estimate for the rotation number can be obtained using the formula
$$\frac{\theta_N-\theta}{N},$$
where $N$ is a large positive integer (sometimes quite a large value is necessary for a good approximation).

Under suitable conditions, the rotation number can be shown to be independent of $\theta_0$.

Write and test functions called `rotation_number1` and `rotation_number2`. Each should take as its argument values of $\Omega$, $K$ and $\theta_0$, and a positive integer value of $N$, which should by default be 10000. Each should return a value of 
$$\frac{\theta_N-\theta}{N}.$$
The first should call only your `sine_map1` function, and the second only your `sine_map2` function.

In [36]:
def rotation_number1(omega = 0.3, k = 1, theta0 = 0.3, N = 10000):
    the = theta0
    for r in range(N):
        the = sine_map1(omega, k, the)
    return (the - theta0) / N

def rotation_number2(omega = 0.3, k = 1, theta0 = 0.3, N = 10000):
    the = theta0
    for r in range(N):
        the = sine_map2(omega, k, the)
    return (the - theta0) / N

In [37]:
# 8 Marks
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question3d(_globals)

Test of rotation_number1 with positional value of N passed!

Test of rotation_number1 with keyword value of N passed!

Test of rotation_number1 with default value of N passed!

The function rotation_number1 does not seem to have a docstring

Test of rotation_number2 with positional value of N passed!

Test of rotation_number2 with keyword value of N passed!

Test of rotation_number2 with default value of N passed!

The function rotation_number2 does not seem to have a docstring

6 out of 8


6

Your second function should work if $K$ and $\theta$ are floats, $N$ is a positive int, and $\Omega$ is a one-dimensional NumPy array. 

Your first function <em>may</em> work in those circumstances, or it may not; this depends on exactly how you've implemented it. (It won't need to, so if it doesn't, don't worry; Phil's doesn't!)

The second function should also work if $\Omega$ and $K$ are floats, $N$ is a positive int, and $\theta$ is a one-dimensional NumPy array, but the first is unlikely to.

You might want to check these things!

For a suitable value of $K$ such as $1$, the plot of the rotation number of the sine map against $\Omega$ is fascinating mathematically. It's an example of a so-called <b>Devil's staircase</b>, which is continuous everywhere, and differentiable with gradient zero <em>almost</em> everywhere (in a certain precise sense), and yet increases from 0 to 1 over the unit interval.

(e) Write test a function called `rotation_number_list`. It should take as its arguments
<ul>
    <li>A list of values of $\Omega$, <code>omega_list</code>.</li>
    <li>Floats representing the values of $K$ and $\theta_0$.</li>
    <li>A positive int, $N$, by default equal to 10000.</li>
</ul>

It should then use your `rotation_number1` function in a suitable loop or comprehension, and return a list consisting of estimates for $\omega_{\Omega,K}(\theta_0)$ for each value of $\Omega$ in `omega_list`. It should make no use at all of NumPy functionality.

In your tests, use fairly short lists of $\Omega$-values and fairly small values of $N$.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
# 3 Marks
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question3e(_globals)

(f) Use your `rotation_number_list` function to create a plot of estimated rotation number against $\Omega$ for 
$$\Omega = 0.00, 0.01, 0.02, \dots , 1.00;$$
use $K=1$, $\theta_0=0.3$ and $N=1000$. Autograding won't be able to help!

<b>Note:</b> you may want to enlarge your diagram by including the line
```python
plt.figure(figsize=(10,10))
```
before `plt.plot(...`

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

(g) Directly use your `rotation_number2` function, which should work fine on 1D NumPy arrays of $\Omega$-values, to create a plot of estimated rotation number against $\Omega$ for 
$$\Omega = 0.00, 0.01, 0.02, \dots , 1.00;$$
use $K=1$, $\theta_0=0.3$ and $N=1000$. Again, autograding won't be able to help!

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

(h) Repeat parts (f) and (g), this time for 
$$\Omega = 0.000, 0.001, 0.002, \dots, 1.000$$
and $N=10000$ (use the same values for $K$ and $\theta_0$). Use the `time` function from the `time` module to time the operations. 

Which of the following statements is true?

<ol>
    <li>The first method, based entirely on comprehensions and loops, and the second method, using vectorization, execute this task in similar time.</li>
    <li>The first method, based entirely on comprehensions and loops, executes this task faster than the second method, using vectorization.</li>
    <li>The first method, based entirely on comprehensions and loops, executes this task slower than the second method, using vectorization.</li>
</ol>

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

question3h_answer = # insert one of 1, 2 or 3

In [ ]:
# 1 Mark
assert(question3h_answer == question3h())
print('test case passed!')

## Question 4 (i)

(a) Create an array called `ints` containing all the integers between 2 and 30 inclusive.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

print(ints)

In [ ]:
# 2 Marks
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question4ia(_globals)

(b) Create, in one line, without using a comprehension, a Boolean array `bool1` consisting of `True` wherever the corresponding element of `ints` is divisible by 5, and `False` everywhere else; it should thus begin, when printed,

```
[False False False  True ...
```

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

print(bool1)

In [ ]:
# 2 Marks
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question4ib(_globals)

(c) In one line, without using a comprehension, create an array `ints2` consisting of all those elements of `ints` that are not divisible by 5. 

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

print(ints2)

In [ ]:
# 2 Marks
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question4ic(_globals)

(d) In one line, without using a comprehension, create an array `ints3` consisting of all those elements of `ints` that are divisible by neither 3 nor 4.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

print(ints3)

In [ ]:
# 2 Marks
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question4id(_globals)

(e) In one line, without using a comprehension, create an array `ints4` consisting of all those elements of `ints` that are either equal to 2 or not divisible by 2.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

print(ints4)

In [ ]:
# 2 Marks
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question4ie(_globals)

(f) Write and test a function called `my_primes2` that takes as its argument an int `n` greater than or equal to 2, and returns a NumPy array consisting of all the primes between 2 and `n` inclusive. Your function should use the Sieve of Eratosthenes, should work using Boolean arrays instead of comprehensions and should not use more iterations than are strictly necessary.

In [ ]:
def my_primes2(n):
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
# 6 Marks
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question4if(_globals)

## Question 4 (ii)

(a) For comparison purposes, write, or get from somewhere, a version called `my_primes1` which uses "core" Python lists instead, and filters using comprehensions instead of Boolean arrays. Test it.

In [ ]:
def my_primes1(n):
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
# 6 Marks
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question4iia(_globals)

Your `my_primes2` function is likely to run much more efficiently than `my_primes1`, but depending on exactly how you've implemented it, we may be able to do even better. There's a video on Blackboard that explains the general approach, and it also cropped up on a bonus question earlier in the module; or you can just follow the steps in this part of the question.

To get started, set up an array of 101 copies of `True`, as follows:

In [ ]:
sieving_array = np.ones(101, dtype='bool')
print(sieving_array)

(b) Make the values of the first two elements of this array (those with index 0 and 1) equal to `False`; do this in one line if you can.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()
print(sieving_array)

In [ ]:
# 1 Mark
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question4iib(_globals)

(c) Make the elements with indexes $4, 6, 8, \dots$ equal to `False`; do this in one line if you can.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()
print(sieving_array)

In [ ]:
# 1 Mark
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question4iic(_globals)

(d) Make the elements with indexes $9, 12, 15, \dots$ equal to `False`; again, in one line if possible. Some of them will already have the value `False`, but don't worry about that.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()
print(sieving_array)

In [ ]:
# 1 Mark
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question4iid(_globals)

(e) Make the elements with indexes $25, 30, 35, \dots$ equal to `False`.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()
print(sieving_array)

In [ ]:
# 1 Mark
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question4iie(_globals)

(f) Make the elements with indexes $49, 56, 63, \dots$ equal to `False`.

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()
print(sieving_array)

In [ ]:
# 1 Mark
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question4iif(_globals)

If you now calculate

In [ ]:
np.arange(101)[sieving_array]

you should see an array of the primes less than or equal to 100.

## Question 4 (iii)
(a) Write, and test, a function called `my_primes3`, which uses logical arrays in the way you've explored in part (ii) of this question to calculate an array of the primes less than or equal to the input `n`.

In [ ]:
def my_primes3(n):
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
# 6 Marks
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question4iiia(_globals)

(b) Using the `time` function from the `time` module, compare the performance of `my_primes1`, `my_primes2` and `my_primes3` on calculating (without printing them) the primes less than or equal to one million.

(Here, autograding simply tests whether the comparative performance of your three functions is what we'd expect.)

In [ ]:
# YOUR CODE HERE
raise NotImplementedError()

In [ ]:
# 3 Marks
# Do not try to delete this cell
# Run this cell for grading
_globals = globals()
question4iiib(_globals)

## Bonus Question

Write a function `first_deriv_approx_data`, which takes as inputs a 1D NumPy array (that is, a vector) of data points `x` and a vector of corresponding $f(x)$ values `y`. The function should return the best possible numerical approximations possible for the values of $f'(x)$ at each value of `x`, in each case using the forward, backward and central difference formulae; the function should use the most accurate formula for each and every point. Should `x` or `y` be empty, then the function should return the string, `'Insufficient Data'`.

In [ ]:
def first_deriv_approx_data(x, y):
    # YOUR CODE HERE
    raise NotImplementedError()

In [ ]:
# Run this test cell to check your code
# Do not delete this cell
# 1 Mark
x = np.array([1.1, 1.2, 1.3, 1.4]) 
y = np.array([9.025013, 11.02318, 13.46374, 16.44465])
npt.assert_array_almost_equal([22.193635, 27.10735 ], first_deriv_approx_data(x, y)[1:-1])
print("Test case passed!!!")

In [ ]:
# Run this test cell to check your code
# Do not delete this cell
# 1 Mark
x = np.array([1.1, 1.2, 1.3, 1.4]) 
y = np.array([9.025013, 11.02318, 13.46374, 16.44465])
npt.assert_almost_equal(19.98167000000003,  first_deriv_approx_data(x, y)[0])
print("Test case passed!!!")

In [ ]:
# Run this test cell to check your code
# Do not delete this cell
# 1 Mark
x = np.array([1.1, 1.2, 1.3, 1.4]) 
y = np.array([9.025013, 11.02318, 13.46374, 16.44465])
npt.assert_almost_equal(29.809100000000036,  first_deriv_approx_data(x, y)[-1])
print("Test case passed!!!")

In [ ]:
# Run this test cell to check your code
# Do not delete this cell
# 1 Mark
x = np.array([1.1, 1.2, 1.3, 1.4]) 
y = np.array([9.025013, 11.02318, 13.46374, 16.44465])
npt.assert_array_almost_equal(np.array([19.98167 , 22.193635, 27.10735 , 29.8091  ]), first_deriv_approx_data(x, y))
print('Test case passed!!!')

In [ ]:
# Run this test cell to check your code
# Do not delete this cell
# 2 Marks

In [ ]:
# Run this test cell to check your code
# Do not delete this cell
# 2 Marks